services:
  web:
    build:
      context: .
      dockerfile: src/backend/GameOfLife.API/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - Data__Path=/app/data/boards.json
    volumes:
      - gol_data:/app/data

volumes:
  gol_data:
